highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "进球啦"

author: "进球啦"
atom-baseurl: "http://www.jinqiula.net"
disqus: ""

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

